name = "raphael-portfolio-backend"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Node.js compatibility for Stripe SDK
compatibility_flags = ["nodejs_compat"]

# Environment variables (secrets)
# You'll add these via CLI: wrangler secret put STRIPE_SECRET_KEY
# [vars]
# Add non-sensitive variables here if needed

# Optional: Custom domain (after deployment)
# routes = [
#   { pattern = "api.raphaelportfolio.com", zone_name = "raphaelportfolio.com" }
# ]

